### PR TITLE
switch donate pathway to Open Collective

### LINKED ISSUE #43: Update donations to go to OpenCollective
Code for DC has changed fiscal sponsors and our donation page no longer works for the new fiscal sponsor. We should update it so that people can donate money to us.

Our previous fiscal sponsor was Code for America. Our new fiscal sponsor is OpenCollective.

OpenCollective has some [documentation on how people can donate](https://docs.opencollective.com/help/financial-contributors/financial-contributors#what-payment-methods-can-i-use). It's not clear at a glance if we'll need to link to our OpenCollective org, or if we can embed a donation form into codefordc.org

This ticket includes:

1. Research OpenCollective's process for collecting contributions. What are our options, technically, for collecting donations?
2. Proposing a technical solution (which could be linking to our OpenCollective profile, or integrating some sort of donation form into codefordc.org
3. Implementing the new donation mechanism

### PR DESCRIPTION
**Pull request by danbjoseph**
addresses #43
could use some graphic design, but perhaps that can happen when edits are made for the name change

Screenshot 2023-08-16 at 8 14 32 PM

### CODE REVIEW

**Comment by sheldon-b** [comment]
@danbjoseph which browser did you use to test this? I'm seeing an issue where the ocf donate button is inside a scrollable box. I'm going to merge this and see if it appears in practice. Either way, it's better than redirecting to code for america. See screenshot below

Screenshot 2023-10-15 at 12 05 56 PM

**Comment by danbjoseph** [comment]
@sheldon-b https://codefordc.org/donate looks okay for me using Firefox, Chrome, Safari, and Mullvad - which browser had the formatting issue?

**Comment by sheldon-b** [comment]
@danbjoseph weird! I'm using Chrome 117.0.5938.149 and see it in production too

**Comment by mkalish** [comment]
@danbjoseph @sheldon-b I also noticed this when we were switching over the domain names

**Pull request merged**
